FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build -- --configuration production

FROM alpine
COPY --from=build /app/dist/vision-alert-ui/browser /app/frontend
VOLUME /app/frontend
