server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  gzip on;
  gzip_types text/plain text/css application/json application/javascript;

  client_max_body_size 600M;

  location / { try_files $uri $uri/ /index.html; }
  location /api/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    client_max_body_size 600M;
  }
  location /ws/ {
    proxy_pass http://backend:8000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
  location ~* /api/cameras/[0-9]+/stream/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    chunked_transfer_encoding on;
  }
  location /media/  { proxy_pass http://backend:8000; }
  location /static/ { proxy_pass http://backend:8000; }
}
