# Generated by Django 4.2.16 on 2026-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_add_entry_line_y'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-triggered_at'], 'verbose_name': 'Alerta'},
        ),
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ['-severity', 'name'], 'verbose_name': 'Regra de Alerta'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('open', 'Aberto'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido')], default='open', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='behavior',
            field=models.CharField(choices=[('motion', 'Detecção de movimento'), ('restricted_zone', 'Pessoa em zona restrita'), ('loitering', 'Permanência prolongada'), ('crowding', 'Aglomeração'), ('night_movement', 'Movimento noturno'), ('fall_detection', 'Queda / pessoa caída'), ('missing_ppe', 'Ausência de EPI'), ('ai_vision', 'Análise por IA'), ('people_counter', 'Contador de pessoas'), ('queue_detection', 'Fila longa'), ('abandoned_object', 'Objeto abandonado'), ('shoplifting_posture', 'Postura suspeita de furto'), ('large_bag', 'Mochila/bolsa grande em zona'), ('running', 'Pessoa correndo'), ('vehicle_pedestrian', 'Veículo em área de pedestre'), ('perimeter_breach', 'Invasão de perímetro'), ('tailgating', 'Passagem não autorizada (tailgating)'), ('lone_child', 'Criança desacompanhada'), ('pool_risk', 'Risco em piscina'), ('bathroom_loiter', 'Permanência longa em banheiro'), ('motionless_person', 'Pessoa imóvel (possível desmaio)'), ('vehicle_zone', 'Veículo em zona proibida'), ('no_hardhat', 'Sem capacete'), ('animal_detection', 'Animal detectado'), ('wrong_way', 'Veículo em sentido errado'), ('parking_violation', 'Veículo parado em local proibido'), ('overcrowded_vehicle', 'Veículo com excesso de pessoas'), ('visitor_counter', 'Contador de visitantes (linha de cruzamento)')], max_length=30, verbose_name='Comportamento'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='cameras',
            field=models.ManyToManyField(blank=True, to='cameras.camera', verbose_name='Câmeras'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='channels',
            field=models.JSONField(default=list, verbose_name='Canais'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='cooldown_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='Cooldown (s)'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parâmetros'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('critical', 'Crítico'), ('high', 'Alto'), ('medium', 'Médio'), ('low', 'Baixo')], default='medium', max_length=10, verbose_name='Severidade'),
        ),
    ]
