# Generated by Django 4.2.16 on 2026-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('value', models.CharField(max_length=500, verbose_name='Valor')),
                ('label', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('value_type', models.CharField(choices=[('str', 'Texto'), ('int', 'Inteiro'), ('float', 'Decimal'), ('bool', 'Booleano')], default='str', max_length=10, verbose_name='Tipo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['key'],
            },
        ),
    ]
