# Generated by Django 4.2.16 on 2026-04-16 22:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_partner_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Mini PC Loja Centro', max_length=120, verbose_name='Nome')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='API Key')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('updating', 'Atualizando'), ('error', 'Erro')], default='offline', max_length=15, verbose_name='Status')),
                ('gpu_model', models.CharField(blank=True, max_length=100, verbose_name='GPU')),
                ('cpu_model', models.CharField(blank=True, max_length=100, verbose_name='CPU')),
                ('ram_total_gb', models.FloatField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('disk_total_gb', models.FloatField(blank=True, null=True, verbose_name='Disco (GB)')),
                ('software_version', models.CharField(blank=True, max_length=30, verbose_name='Versao software')),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('gpu_percent', models.FloatField(blank=True, null=True)),
                ('ram_percent', models.FloatField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('cameras_active', models.IntegerField(default=0)),
                ('cameras_total', models.IntegerField(default=0)),
                ('uptime_seconds', models.IntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo heartbeat')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo sync')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP publico')),
                ('local_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP local')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Dispositivo Edge',
                'verbose_name_plural': 'Dispositivos Edge',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fleet.edgedevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='fleet_devic_device__71cc27_idx')],
            },
        ),
    ]
