# Generated by Django 4.2.16 on 2026-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['company_name'], 'verbose_name': 'Revenda', 'verbose_name_plural': 'Revendas'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['company_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='display_name',
            field=models.CharField(max_length=50, verbose_name='Nome exibido'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(default=dict, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_cameras',
            field=models.PositiveIntegerField(default=1, verbose_name='Máx. câmeras'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_rules',
            field=models.PositiveIntegerField(default=3, verbose_name='Máx. regras'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(default=2, verbose_name='Máx. usuários'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço mensal (R$)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Dias de trial'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Asaas Customer ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado')], default='trial', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial expira em'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de alertas'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chat ID Telegram'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Token Telegram'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
