# Generated by Django 4.2.16 on 2026-04-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name'], 'verbose_name': 'Câmera', 'verbose_name_plural': 'Câmeras'},
        ),
        migrations.AlterModelOptions(
            name='camerazone',
            options={'verbose_name': 'Zona'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último contato'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='protocol',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('http', 'HTTP/MJPEG'), ('local', 'Webcam Local'), ('file', 'Arquivo de Vídeo'), ('youtube', 'YouTube')], default='rtsp', max_length=10, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/', verbose_name='Snapshot'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Erro'), ('alert', 'Alerta')], default='offline', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL / Endereço'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='camerazone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='camerazone',
            name='is_restricted',
            field=models.BooleanField(default=True, verbose_name='Zona restrita'),
        ),
        migrations.AlterField(
            model_name='camerazone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da zona'),
        ),
        migrations.AlterField(
            model_name='camerazone',
            name='points',
            field=models.JSONField(default=list, verbose_name='Pontos'),
        ),
        migrations.CreateModel(
            name='CameraMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('people_count', 'Contagem de pessoas'), ('queue_size', 'Tamanho da fila'), ('vehicle_count', 'Contagem de veículos'), ('alert_count', 'Alertas disparados'), ('motion_score', 'Nível de movimento')], max_length=30)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cameras.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['camera', 'metric_type', 'timestamp'], name='cameras_cam_camera__a12357_idx')],
            },
        ),
    ]
