# Generated by Django 4.2.16 on 2026-04-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('cameras', '0002_alter_camera_options_alter_camerazone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='location_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='locations.location'),
        ),
    ]
