# Generated by Django 4.2.16 on 2026-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_location_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='entry_line_y',
            field=models.FloatField(blank=True, help_text='Posição vertical da linha de contagem (0=topo, 1=base)', null=True, verbose_name='Linha de entrada (0-1)'),
        ),
    ]
