# Generated by Django 4.2.16 on 2026-04-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_entry_line_y'),
    ]

    operations = [
    ]
