# Generated by Django 4.2.16 on 2026-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_add_entry_line_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=500, verbose_name='Senha'),
        ),
    ]
