# Generated by Django 4.2.16 on 2026-04-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0002_alter_camera_options_alter_camerazone_options_and_more'),
        ('tenants', '0002_alter_partner_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso horário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('entries', models.PositiveIntegerField(default=0)),
                ('exits', models.PositiveIntegerField(default=0)),
                ('peak_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peak_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_counts', to='cameras.camera')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_counts', to='locations.location')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('camera', 'date')},
            },
        ),
    ]
